sudo: false
language: node_js
env: TEST_SUITE=unit
node_js:
  - "5.6.0"
cache:
  directories:
    - node_modules
install:
  - npm install
notifications:
  email: false
before_script:
  - "wget http://selenium.googlecode.com/files/selenium-server-standalone-2.31.0.jar"
  - "java -jar selenium-server-standalone-2.31.0.jar > /dev/null &"
  - sleep 5

script: "npm run test:ci:$TEST_SUITE"
script: "npm run test:ci:functional"
