version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
    - checkout
    - run:
        name: updatenpm
        command: 'sudo npm install -g npm@latest'
    - run:
        name: install
        command: npm install
    - run:
        name: test
        command: npm run test:ci
workflows:
  version: 2
  test_and_build:
    jobs: