version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
    - checkout
    - run:
        name: install
        command: npm install
    - run:
        name: build
        command: npm run build
    - run:
        name: bundlesize
        command: npm run bundlesize
  jest:
    docker:
      - image: circleci/node:latest
    steps:
    - checkout
    - run:
        name: install
        command: npm install
    - run:
        name: jest
        command: npm run jest -- --forceExit --detectOpenHandles --runInBand
  eslint:
    docker:
      - image: circleci/node:latest
    steps:
    - checkout
    - run:
        name: install
        command: npm install
    - run:
        name: lint
        command: npm run lint
  typescript:
    docker:
      - image: circleci/node:latest
    steps:
    - checkout
    - run:
        name: install
        command: npm install
    - run:
        name: lint
        command: npm run type
workflows:
  version: 2
  test_and_build:
    jobs:
      - build
      - jest
      - eslint
      - typescript
