version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
    - checkout
    - run:
        name: install
        command: npm install
    - run:
        name: rebuildSass
        command: npm rebuild node-sass
    - run:
        name: build
        command: npm run build
    - run:
        name: bundlesize
        command: npm run bundlesize
  test:
    docker:
      - image: circleci/node:latest
    steps:
    - checkout
    - run:
        name: install
        command: npm install
    - run:
        name: lint
        command: npm run lint
    - run:
        name: jest
        command: npm run jest -- --forceExit --detectOpenHandles --runInBand
    - run:
        name: typescript
        command: npm run type
workflows:
  version: 2
  test_and_build:
    jobs:
      - build
      - test
