version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
    - checkout
    - run:
        name: install
        command: npm install
    - run:
        name: test
        command: npm run test
    - run:
        name: rebuildSass
        command: npm rebuild node-sass
    - run:
        name: buildClient
        command: npm run build:client
    - run:
        name: buildServer
        command: npm run build:server   
workflows:
  version: 2
  test_and_build:
    jobs: